# Programación 201

Librerías científicas en Python: `NumPy`
------------------------------------------------------

### Ejercicio 1
Calculad la norma y el determinante de la siguiente matriz: ```[[1, 0], [2, -1]]```.

In [ ]:
import numpy as np

In [ ]:
matriz =np.array([[1, 0],[2, -1]])
matriz


array([[ 1,  0],
       [ 2, -1]])

In [ ]:
#Norma. https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html
norma=np.linalg.norm(matriz)
norma


2.449489742783178

In [ ]:
# DETERMINANTE:
#https://www.geeksforgeeks.org/how-to-calculate-the-determinant-of-a-matrix-using-numpy/
det= np.linalg.det(matriz)
det

-1.0

### Ejercicio 2 
Evaluad las funciones arcoseno y arcocoseno en el intervalo [0,1] y con paso (resolución) de 0.1 y guardadlas en dos _arrays_.

In [ ]:
# ARCOSENO
# https://numpy.org/doc/stable/reference/generated/numpy.arccos.html
arcoseno= np.arccos([0,1])
arcoseno


array([1.57079633, 0.        ])

In [ ]:
# ARCOCOSENO.
# 

### Ejercicio 3
Generad una lista de 100 valores enteros aleatorios de 0-9. Realizad los siguientes cálculos utilizando métodos de _numpy_:
- Media y desviación estándar de los valores de la lista
- Valor máximo y mínimo
- Sumad todos los valores de la lista
- Conseguid una lista de valores únicos

In [ ]:
# Generamos la lista
import random
n=100
Lista = [random.randint(0,9) for _ in range(n)]
print(Lista)

[9, 6, 1, 6, 3, 8, 1, 1, 3, 8, 7, 9, 9, 0, 4, 5, 0, 0, 2, 6, 9, 0, 3, 7, 9, 1, 7, 7, 1, 0, 0, 8, 7, 0, 8, 9, 8, 8, 7, 4, 8, 7, 0, 6, 6, 5, 1, 8, 5, 3, 5, 2, 7, 8, 3, 4, 5, 7, 8, 0, 1, 4, 5, 5, 5, 1, 2, 9, 3, 3, 4, 8, 0, 9, 3, 0, 0, 9, 8, 5, 6, 1, 1, 2, 1, 8, 1, 6, 6, 3, 9, 3, 5, 6, 7, 6, 4, 7, 4, 4]


In [ ]:
# Media
#https://www.delftstack.com/es/api/numpy/python-numpy-mean/
media=np.mean(Lista)
media

4.63

In [ ]:
# desviacion estándar.
# https://www.delftstack.com/es/api/numpy/python-numpy-std/
desv= np.std(Lista)
desv


2.9888292022127994

In [ ]:
# valor máximo:
maximo=np.amax(Lista)
maximo


9

In [ ]:
#Valor mínimo:
minimo=np.amin(Lista)
minimo


0

In [ ]:
# sumas todos los elementos de una lista:
suma=np.sum(Lista)
suma

463

In [ ]:
# Conseguid una lista de valores únicos:
# https://www.analyticslane.com/2019/10/16/numpy-basico-localizar-valores-unicos-en-arrays-numpy/

unicos=np.unique(Lista)
unicos


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Ejercicio 4
Ordenad la matriz bidimensional ```[[5,1,7], [0,7,4], [7,23,1]]``` por filas utilizando como algoritmo de ordenación el [Merge sort](https://en.wikipedia.org/wiki/Merge_sort).

**Hint:** No es necesario que implementéis el algoritmo de ordenación a mano, NumPy contiene métodos para realizar diferentes tipos de ordenación sobre diferentes estructuras de datos.

In [ ]:
# https://runestone.academy/runestone/books/published/pythonds/SortSearch/TheMergeSort.html
matriz=np.array([[5,1,7], [0,7,4], [7,23,1]])
matriz


array([[ 5,  1,  7],
       [ 0,  7,  4],
       [ 7, 23,  1]])

In [ ]:
# Ordenamos los elementos de la matriz:
np.sort(matriz)

array([[ 1,  5,  7],
       [ 0,  4,  7],
       [ 1,  7, 23]])

### Formas de ordenar datos en Numpy:
  numpy.sort
Return a sorted copy of an array.

numpy.argsort
Indirect sort.

numpy.lexsort
Indirect stable sort on multiple keys.

numpy.searchsorted
Find elements in sorted array.

numpy.partition
Partial sort

In [ ]:
# dividimos la matriz en dos con el método spilt:
np.array_spilt(matriz,2)

### Ejercicio 5
Definid una función que dadas dos matrices, devuelva el valor absoluto de la multiplicación de los determinantes ambas, es decir, dadas A y B, nuestra función devolverá `|det(A) * det(B)|`.

In [ ]:
a=np.random.rand(2,2)
b=np.random.rand(4,4)

def Multiplicacion_determinantes():
  a=np.random.rand(2,2)
  b=np.random.rand(4,4)

  det_a=np.linalg.det(a)
  det_b=np.linalg.det(b)
  return (det_a) * (det_b)
Multiplicacion_determinantes 

<function __main__.Multiplicacion_determinantes>

In [ ]:
a=np.random.rand(2,2)
b=np.random.rand(4,4)

det_a=np.linalg.det(a)
det_b=np.linalg.det(b)
mult= (det_a) * (det_b)
mult

0.03158809161014985

In [ ]:
#El valor absoluto (o módulo de un número real cualquiera) es el mismo número pero con signo positivo. 


### Ejercicio 6
Cread una matriz 10x10 que corresponda con la [matriz identidad](https://es.wikipedia.org/wiki/Matriz_identidad) usando generadores básicos de arrays. Cread una matriz identidad 10x10 (esta vez usando generadores especificos de matrices identidad) y comprobad que ambas matrices son iguales

**Consideraciones**:
- La primera matriz debe crearse usando constructores básicos de arrays, como los presentados en los Notebooks de teoría.
* La segunda matriz debe generarse utilizando el generador de matrices identidad de numpy.
* La comparación debe devolver True si las matrices son iguales (un único True), False de no ser así.

In [ ]:
Matriz=np.zeros((10,10))
Matriz

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
Matriz_identidad=np.identity(10)
Matriz_identidad

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
def Comparar_Matrices():
  Matriz=np.zeros((10,10))
  Matriz_identidad=np.identity(10)
  if Matriz == Matriz_identidad:
   return True
  else:
    return False
Comparar_Matrices

<function __main__.Comparar_Matrices>

### Ejercicio 7
Cread una matriz de 2x6 donde los valores de cada posición `(i, j)` correspondan a `i^2+j` para todo `i` par, `i/j^2` para todo `i` impar.

In [ ]:
# 2*6 ... 2 filas, 6 columnas
matrix=[]

for i in range(2):
      matrix.append([i]*6)
matrix    

[[0, 0, 0, 0, 0, 0], [1, 1, 1, 1, 1, 1]]

In [ ]:
matrix=[]
for i in range(2):
  matrix.append([i]*6)
  for j in range(6):
    matrix[i][j]
matrix

[[0, 0, 0, 0, 0, 0], [1, 1, 1, 1, 1, 1]]

In [ ]:
# i numero par o impar
  if i%2 ==0:
    return i^2+j
    else :
    return i/j^2


### Ejercicio 8
Cread dos matrices de tamaño 5x5 con números reales aleatorios. Obtened el resultado de multiplicar ambas matrices usando los dos métodos de multiplicación de matrices vistos en el Notebook de teoría. ¿Cuál es la diferencia entre ambos resultados? Cread ahora dos matrices de tamaño 4x5 y 5x5 respectivamente, repetid la operación. Describid cuál de los métodos de multiplicación podéis aplicar y porqué

In [ ]:
A=np.random.random((5,5))
A

array([[0.28500825, 0.82698184, 0.28723625, 0.11243862, 0.35208869],
       [0.36132508, 0.09781877, 0.49349625, 0.01167839, 0.62267925],
       [0.0837105 , 0.990163  , 0.45230175, 0.47106491, 0.94364088],
       [0.93975506, 0.17495478, 0.50158379, 0.685713  , 0.44467561],
       [0.59986375, 0.02189337, 0.30527836, 0.92440769, 0.48555822]])

In [ ]:
B=np.random.random((5,5))
B

array([[0.22452851, 0.27329144, 0.70776683, 0.60081353, 0.34061005],
       [0.58451159, 0.2411221 , 0.64955424, 0.40445974, 0.39282103],
       [0.21504069, 0.91406049, 0.24371993, 0.21182761, 0.49031887],
       [0.7950901 , 0.81406791, 0.70166247, 0.65314998, 0.47311753],
       [0.68292588, 0.7373345 , 0.10718985, 0.83090668, 0.54938139]])

In [ ]:
#Ahora multiplicamos las matrices de una forma:
print(A*B)

[[0.06399248 0.22600706 0.20329629 0.06755464 0.11992495]
 [0.2111987  0.02358627 0.32055259 0.00472344 0.2446015 ]
 [0.01800116 0.90506887 0.11023495 0.09978455 0.46268493]
 [0.74718995 0.14242507 0.35194252 0.44787343 0.21038382]
 [0.40966247 0.01614273 0.03272274 0.76809653 0.26675665]]


In [ ]:
# ahora multiplicamos de la otra forma:
print(A.dot(B))

[[0.93898974 0.89098503 0.92552845 0.93255436 0.80939754]
 [0.67895491 1.04204865 0.51448657 0.88620497 0.7510804 ]
 [1.71379625 1.75431651 1.24432434 1.63833901 1.38052937]
 [1.27000993 1.64358202 1.42981984 1.55898638 1.20347128]
 [1.27971839 1.55880895 1.21385611 1.44115805 1.06671367]]


In [ ]:
# ¿Cuál es la diferencia entre ambos resultados?

In [ ]:
# matrices de 4*5 y 5*5
C=np.random.random((4,5))
C

array([[0.55309887, 0.13866606, 0.1837862 , 0.94632866, 0.36098807],
       [0.38034949, 0.87912008, 0.23710754, 0.53529708, 0.90666129],
       [0.91548767, 0.87922861, 0.27140372, 0.68005119, 0.16406925],
       [0.14611246, 0.6493858 , 0.31889316, 0.06736963, 0.84659967]])

In [ ]:
D=np.random.random((5,5))
D

array([[0.70709942, 0.99348065, 0.39557325, 0.02744182, 0.4971813 ],
       [0.81326312, 0.96921051, 0.00770808, 0.03790267, 0.48111535],
       [0.05223806, 0.40998054, 0.75779556, 0.99591838, 0.80844565],
       [0.05107231, 0.18725308, 0.02946291, 0.53098966, 0.56751879],
       [0.09234856, 0.34534891, 0.43783324, 0.25378893, 0.12689449]])

In [ ]:
#Multiplicamos
print(C*D)


ValueError: ignored

In [ ]:
print(C.dot(D))

[[0.59513644 1.06110819 0.5450665  0.79757542 1.07315263]
 [1.1073546  1.74048227 0.74964931 0.79423605 1.22259084]
 [1.42644595 2.05694996 0.66645939 0.73148283 1.50435021]
 [0.7297189  1.21027889 0.6771139  0.5968448  0.78854401]]
